# Generated by Django 2.2.5 on 2019-11-12 17:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portalapp', '0002_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Тескт статьи'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='deslikes',
            field=models.PositiveIntegerField(default=0, verbose_name='дизлайки'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='article',
            name='likes',
            field=models.PositiveIntegerField(default=0, verbose_name='лайки'),
        ),
        migrations.AlterField(
            model_name='article',
            name='realized',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок статьи'),
        ),
        migrations.CreateModel(
            name='Coomment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=50, verbose_name='')),
                ('commetn_text', models.CharField(max_length=250, verbose_name='')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portalapp.Article')),
            ],
        ),
    ]
